### ISSUE TITLE
configmap can not be UnmarshalConfig

### ISSUE THREAD

**Issue by WintonChan** [go-chassis/go-archaius#149]
**Describe the bug**
use archaius to parse configmap
```
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: roboartisan-robooperationmanagement-config
          labels:
            name: roboartisan-robooperationmanagement-config
        data:
            database.ip: 0.0.0.0
            database.port: 5432
            database.user_name: root
```

the struct database

```
type Database struct {
	UserName string `json:"user_name"`
	Password string `json:"password"`
	IP       string `json:"ip"`
	Port     int    `json:"port"`
	DBName   string `json:"db_name"`
	SslMode  string `json:"ssl_mode"`
	MaxIdle  int    `json:"max_idle"`
	MaxConn  int    `json:"max_conn"`
}
```

After archaius.UnmarshalConfig ，string type data can be parse, but int type data fail to parse  
**Version of go chassis**
v1.5.4
**To Reproduce**

**Logs**
 #``
